### ISSUE TITLE
SpaceX Dashboard Challenge

### ISSUE THREAD

**Issue by apoorvo** [apoorvo/spacex-dashboard#1]
https://public.3.basecamp.com/p/UGEyqrnc11MEXx8ndGmJcA49

**Comment by apoorvo** [comment]
Deploy Link : https://bigbinary-spacex-apoorvo.herokuapp.com/

**Comment by apoorvo** [comment]
The application is ready for the code review.

**Comment by vinay0x** [comment]
Please pick a timeslot for your technical interview: https://calendly.com/bigbinary/technical-interview

**Comment by apoorvo** [comment]
Hi Vinay, thank you for the opportunity. I have selected the slot for 24th May as currently I am not at my place. I am stuck in a family emergency but I will be definitely available then.
